spring:
  application:
    name: caju-authorizer
  cache:
    type: redis

  jpa:
    hibernate:
      ddl-auto: update
    database: mysql
    database-platform: org.hibernate.dialect.MySQL57Dialect
#    properties:
#      hibernate:
#        show_sql: true
#        format_sql: true
  datasource:
    url: ${DATABASE_URL:jdbc:mysql://localhost:3306/miniautorizador}
    username: root
    password:
    hikari:
      maximum-pool-size: 30
      minimum-idle: 10
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000

server:
  error:
    include-stacktrace: never

spring-doc:
  api-docs:
    enabled: true
    path: /api/docs
  swagger-ui:
    path: /api/docs/swagger-ui
    enabled: true
#    tagsSorter: alpha
#    operationsSorter: method

logging:
  level:
    org:
      hibernate:
        type: trace
    com:
      authorizer: debug

espoc:
  idempotency:
    paths: >
      /transactions/authorization
    ttlInMinutes: 60