spring:
  application:
    name: caju-authorizer
  cache:
    type: redis

  jpa:
    hibernate:
      ddl-auto: none
#    database: mysql
#    database-platform: org.hibernate.dialect.MySQL57Dialect
#    properties:
#      hibernate:
#        show_sql: true
#        format_sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/miniautorizador
    username: miniautorizador
    password: miniautorizador
    hikari:
      maximum-pool-size: 30
      minimum-idle: 10
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000

  flyway:
    baseline-description: true
    baseline-on-migrate: true
    create-schemas: true
    default-schema: public
    enabled: true
    locations: filesystem:src/main/resources/db/migration/


server:
  error:
    include-stacktrace: never

spring-doc:
  api-docs:
    enabled: true
    path: /api/docs
  swagger-ui:
    path: /api/docs/swagger-ui
    enabled: true
#    tagsSorter: alpha
#    operationsSorter: method

logging:
  level:
    org:
      hibernate:
        type: trace
    com:
      authorizer: debug

espoc:
  idempotency:
    paths: >
      /transactions/authorization
    ttlInMinutes: 60