spring:
  application:
    name: caju-authorizer
  cache:
    type: redis

  jpa:
    hibernate:
      ddl-auto: update
    database: mysql
    database-platform: org.hibernate.dialect.MySQL57Dialect
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  datasource:
    url: ${DATABASE_URL:jdbc:mysql://localhost:3306/miniautorizador}
    username: root
    password:

server:
  error:
    include-stacktrace: never

spring-doc:
  api-docs:
    enabled: true
    path: /api/docs
  swagger-ui:
    path: /api/docs/swagger-ui
    enabled: true
#    tagsSorter: alpha
#    operationsSorter: method

logging:
  level:
    org:
      hibernate:
        type: trace
    com:
      authorizer: debug

espoc:
  idempotency:
    paths: >
      /transactions/authorization
    ttlInMinutes: 60