spring:
  application:
    name: caju-authorizer
  cache:
    type: redis

  jpa:
    hibernate:
      ddl-auto: none
#    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/miniautorizador?createDatabaseIfNotExist=true
    username: miniautorizador
    password: miniautorizador
    hikari:
      maximum-pool-size: 30
      minimum-idle: 10
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000

  flyway:
    baseline-on-migrate: true
    enabled: true
    locations: classpath:db/migration



server:
  error:
    include-stacktrace: never

spring-doc:
  api-docs:
    enabled: true
    path: /api/docs
  swagger-ui:
    path: /api/docs/swagger-ui
    enabled: true
#    tagsSorter: alpha
#    operationsSorter: method

logging:
  level:
    org:
      flywaydb: debug
      hibernate:
        type: trace
    com:
      authorizer: debug
    sql: debug
    root: debug

espoc:
  idempotency:
    paths: >
      /transactions/authorization
    ttlInMinutes: 60