version: "3.7"

services:

#  mysql:
#    image: mysql:5.7
#    hostname: mysql
#    container_name: mysql-miniautorizador
#    restart: always
#    ports:
#      - "3306:3306"
#    environment:
#      MYSQL_DATABASE: miniautorizador
#      MYSQL_ROOT_PASSWORD:
#      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"

  postgres:
    image: postgres:latest
    container_name: postgres-miniautorizador
    environment:
      POSTGRES_USER: miniautorizador
      POSTGRES_PASSWORD: miniautorizador
      POSTGRES_DB: miniautorizador
    ports:
      - "5432:5432"
    volumes:
      - postgres-miniautorizador:/var/lib/postgresql

  redis:
    image: redis:7-alpine
    restart: always
    ports:
      - "6379:6379"
    environment:
      REDIS_PASSWORD: secret
  redis-insight:
    image: redis/redisinsight:latest
    restart: always
    ports:
      - "5540:5540"
    volumes:
      - redis-insight:/data

volumes:
  redis-insight:
  postgres-miniautorizador: